-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
-- vim.cmd([[
-- " Latex specification
-- au BufNewFile,BufRead *.tex
--     \ set nocursorline |
--     \ set nornu |
--     \ set number |
--     \ let g:loaded_matchparen=1 |
-- ]])
